# Generated by Django 3.1.3 on 2021-03-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='name',
            new_name='title',
        ),
    ]
